# Generated by Django 6.0.6 on 2026-06-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('dark-room', 'Dark Room'), ('studio-suite', 'Studio Suite'), ('loft-suite', 'Loft Suite'), ('family-studio', 'Family Studio'), ('family-suite', 'Family Suite'), ('family-ultimate', 'Ultimate Family Suite'), ('obsidian-suite', 'Obsidian Suite'), ('penthouse', 'Void Penthouse')], max_length=30)),
                ('floor', models.PositiveSmallIntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('booked', 'Booked'), ('maintenance', 'Maintenance')], default='vacant', max_length=20)),
                ('is_clean', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('max_guests', models.PositiveSmallIntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['floor', 'room_number'],
            },
        ),
    ]
