# Generated by Django 6.0.6 on 2026-06-20 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelocationOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(choices=[('same', 'Same Type — No Compensation'), ('upgrade', 'Free Upgrade — No Compensation'), ('downgrade', 'Downgrade — Compensation Due'), ('none', 'No Room Available — Cancel or Reschedule')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Awaiting Guest Decision'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('bonus_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_nights', models.PositiveSmallIntegerField(default=0)),
                ('guest_choice', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocations', to='bookings.booking')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocation_offers', to=settings.AUTH_USER_MODEL)),
                ('new_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relocations_to', to='rooms.room')),
                ('original_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relocations_from', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Relocation Offer',
                'verbose_name_plural': 'Relocation Offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
