# Generated by Django 6.0.6 on 2026-06-18 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciergeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('theatre', 'Theatre & Culture'), ('flowers', 'Flowers & Gifting'), ('shopping', 'Personal Shopping'), ('yacht', 'Yacht & Private Jet'), ('security', 'Privacy & Security'), ('pets', 'Pet Services'), ('photography', 'Photography & Film'), ('restaurant', 'Restaurant Reservation'), ('other', 'Something Else')], max_length=30)),
                ('detail', models.TextField()),
                ('requested_time', models.DateTimeField(blank=True, null=True)),
                ('proposed_time', models.DateTimeField(blank=True, null=True)),
                ('confirmed_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('proposed', 'Time Proposed — Awaiting Guest'), ('confirmed', 'Confirmed'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('staff_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concierge_requests', to=settings.AUTH_USER_MODEL)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concierge Request',
                'verbose_name_plural': 'Concierge Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
