# Generated by Django 6.0.6 on 2026-06-11 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('guest', 'Guest'), ('receptionist', 'Receptionist'), ('manager', 'Manager')], default='guest', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('loyalty_tier', models.CharField(choices=[('obsidian', 'Obsidian'), ('gold', 'Gold'), ('diamond', 'Diamond')], default='obsidian', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
