# Generated by Django 6.0.6 on 2026-06-20 11:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('minor', 'Minor (same day)'), ('furniture', 'Broken Furniture (1-2 days)'), ('plumbing', 'Plumbing (2-3 days)'), ('electrical', 'Electrical (2-3 days)'), ('deepclean', 'Deep Clean / Pest (1-2 days)'), ('major', 'Major / Structural (7+ days)')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('started', models.DateField(default=django.utils.timezone.now)),
                ('expected_ready', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('cleared', 'Cleared')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_cleared', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_created', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Maintenance Log',
                'verbose_name_plural': 'Maintenance Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('check-in', 'Checked In'), ('check-out', 'Checked Out'), ('clean', 'Marked Clean'), ('dirty', 'Marked Needs Cleaning'), ('maint-set', 'Set Maintenance'), ('maint-extend', 'Extended Maintenance'), ('maint-clear', 'Cleared Maintenance'), ('relocation', 'Recorded Relocation Decision')], max_length=20)),
                ('detail', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='rooms.room')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Action Log',
                'verbose_name_plural': 'Staff Action Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
