# Generated by Django 6.0.6 on 2026-06-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending-payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('due-in', 'Due In'), ('checked-in', 'Checked In'), ('checked-out', 'Checked Out'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded')], default='confirmed', max_length=20),
        ),
    ]
