# Generated by Django 6.0.6 on 2026-06-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='membership_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
